version: "3.8"

x-env: &env
  environment:
    DATABASE_URL: postgres://test_user:test_password@db_dev:5432/postgres_dev
    REDIS_URL: redis://message_broker_store_dev
    RABBITMQ_URL: pyamqp://guest@message_broker_dev//
    FRONTEND_URL: http://localhost:8000
    SECRET_KEY: super_secret
    ENV: dev
  env_file:
    - backend/.env.local.dev

services:
  backend:
    <<: *env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ././backend:/home/user/app/
    ports:
      - 8001:8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  celery_worker:
    <<: *env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ././backend:/home/user/app/
    command: >
      sh -c "pip install -e . &&
             celery -A backend.celery.main worker -l INFO -E"

  celery_beat:
    <<: *env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ././backend:/home/user/app/
    command: >
      sh -c "pip install -e . &&
             celery -A backend.celery.main beat"

  db_dev:
    image: "postgres:10.15-alpine"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: postgres_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data:rw
    ports:
      - 8004:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user", "-d", "postgres_dev"]
      interval: 30s
      timeout: 3s
      retries: 30
      start_period: 15s

  message_broker_dev:
    image: "rabbitmq:3.12.0-alpine"
    ports:
      - 8005:5672

  message_broker_store_dev:
    image: "redis:7.0.11-alpine"
    ports:
      - 8006:6379

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    working_dir: /home/node/app
    volumes:
      - ./frontend/tsconfig.json:/home/node/app/tsconfig.json
      - ./frontend/src:/home/node/app/src
      - ./frontend/public:/home/node/app/public
      - ./frontend/package.json:/home/node/app/package.json
      - ./frontend/package-lock.json:/home/node/app/package-lock.json
      - node_modules_cache_frontend:/home/node/app/node_modules
    environment:
      PORT: 8000
      REACT_APP_BACKEND_URL: http://localhost:8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    command: /bin/sh -c "npm install && npm start"
    ports:
      - 8000:8000

  entrypoint:
    image: "busybox:latest"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

volumes:
  pgdata_dev:
  node_modules_cache_frontend:
