[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["wolfgang000 <wolfgangsalazarmora@gmail.com>"]
readme = "README.md"
packages = [{include = "backend", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.97.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.16"}
psycopg = {extras = ["binary", "pool"], version = "^3.1.9"}
result = "^0.10.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
