[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["wolfgang000 <wolfgangsalazarmora@gmail.com>"]
readme = "README.md"
packages = [{include = "backend", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.101.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.19"}
psycopg = {extras = ["binary", "pool"], version = "^3.1.10"}
result = "^0.13.1"
httpx = "^0.24.1"
alembic = "^1.11.3"
celery = "^5.3.1"
redis = "^5.0.0"
feedparser = "^6.0.10"
aiofiles = "^23.2.1"
oauthlib = "^3.2.2"
itsdangerous = "^2.1.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.1"
black = "^23.7.0"
mypy = "^1.5.1"
anyio = {extras = ["trio"], version = "^3.7.1"}
types-aiofiles = "^23.2.0.0"
pytest-mock = "^3.11.1"
types-oauthlib = "^3.2.0.9"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
