[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["wolfgang000 <wolfgangsalazarmora@gmail.com>"]
readme = "README.md"
packages = [{include = "backend", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.97.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.16"}
psycopg = {extras = ["binary", "pool"], version = "^3.1.9"}
result = "^0.10.0"
httpx = "^0.24.1"
alembic = "^1.11.1"
celery = "^5.3.1"
redis = "^4.5.5"
feedparser = "^6.0.10"
aiofiles = "^23.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
black = "^23.3.0"
mypy = "^1.3.0"
anyio = {extras = ["trio"], version = "^3.7.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
