name: Backend CI

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: backend

env:
  DATABASE_URL: postgres://test_user:test_password@localhost:5432/postgres_dev
  ENV: test
  REDIS_URL: redis://localhost
  RABBITMQ_URL: redis://localhost
  GOOGLE_CLIENT_ID: abc
  GOOGLE_CLIENT_SECRET: abc
  GOOGLE_REDIRECT_URI: abc
  FRONTEND_URL: http://localhost:8000
  SECRET_KEY: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: postgres_dev
        image: postgres:12
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.5.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check format
        run: poetry run black src tests

      - name: Check types
        run: poetry run mypy src tests

      - name: Run tests
        run: poetry run pytest
