name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    name: Build and test
    runs-on: self-hosted
    env:
      ImageOS: ubuntu20

    steps:
      - uses: actions/checkout@v3
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Prettier checks
        run: npx prettier --check .

      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
